### ISSUE TITLE
Not Updated for 1.21

### ISSUE THREAD

**Issue by AllOutJay** [crossy-l/VanillaPings#1]
Hi there,

Is there any chance you'll be updating this for 1.21?

Best regards,
Jay

**Comment by crossy-l** [comment]
Hey AllOutJay,

yes I am working on an update right now, shouldn't take long.

Best regards,
Crossy

**Comment by crossy-l** [comment]
Hey,

I updated the mod to Minecraft version **1.21** and **1.21.1.** You can find the download on [Modrinth](https://modrinth.com/mod/vanilla-pings/version/Bs1VXoHR) as well as on the latest [Github release](https://github.com/crossy-l/VanillaPings/releases/tag/v1.10).

Sorry for having you wait so long, I was logged out of my account and didn't receive any notifications. I still plan on updating the mod so if you have any issues or versions you need supported just let me know.

Best regards,
Crossy
